### ISSUE TITLE
make sure bocado runs

### ISSUE THREAD

**Issue by etosch** [ameetrivedi/bocado#1]
Now that you have the package installed locally, try profiling a program using the instructions in the readme, just to see what the output looks like. Pick something simple just to get an idea of what the program is doing.

**Comment by ameetrivedi** [comment]
>>> import sys
>>> import subprocess
>>> from bocado import classes
>>> from bocado import value_sampler
>>> execfile('newtonSqrt.py')
3.16231942215
3.16227766017
3.16227766017
>>> sys.settrace(None)
>>> sys.settrace(None)
>>> from bocado import output
>>> with file('type_output.txt', 'a') as f:
...   output.pretty_print_types(stream=f)
... 
>>> 


Runs without any error but could not dump the sampling output. I think I missed doing something. I did start sampling.

**Comment by etosch** [comment]
did it create the file?
