### ISSUE TITLE
fix test: part 1

### ISSUE THREAD

**Issue by etosch** [ameetrivedi/bocado#3]
`cd tests; python -m unittest -v classes_test` fails:

```
======================================================================
ERROR: test_signaturenature (classes_test.FunctionRefTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "classes_test.py", line 190, in test_signaturenature
    fn.set_signaturenature()
AttributeError: 'FunctionRef' object has no attribute 'set_signaturenature'
```

`fn.set_signaturenature()` just needs to be changed to `fn.set_signature()`

**Comment by ameetrivedi** [comment]
Completed.

Output after fixing the issue:

guest087:tests ameetrivedi$ !pyth
python2.7 -m unittest -v classes_test
test_get_type (classes_test.ArgRefTest) ... ok
test_get_type_prob (classes_test.ArgRefTest) ... ok
test_arity (classes_test.FunctionRefTest) ... ok
test_get_key (classes_test.FunctionRefTest) ... ok
test_get_num_samples (classes_test.FunctionRefTest) ... ok
test_get_return (classes_test.FunctionRefTest) ... ok
test_init (classes_test.FunctionRefTest) ... ok
test_signature (classes_test.FunctionRefTest) ... ok
test_builtin_type_sample (classes_test.InstanceSetTest) ... ok
test_instance_sample (classes_test.InstanceSetTest) ... ok
test_init (classes_test.ParameterizedDictTest) ... ok
test_init (classes_test.ParameterizedTupleTest) ... ok
test_get_list (classes_test.ParameteterizedListTest) ... ok
test_get_collection (classes_test.ParametricTypeTest) ... ok
test_init (classes_test.TaggedUnionTest) ... FAIL
test_dict_vcd (classes_test.ValueCollectionDictTest) ... ok
test_list_vcd (classes_test.ValueCollectionDictTest) ... ok
test_set_vcd (classes_test.ValueCollectionDictTest) ... ok
test_tuple_vcd (classes_test.ValueCollectionDictTest) ... ok

======================================================================
FAIL: test_init (classes_test.TaggedUnionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "classes_test.py", line 272, in test_init
    self.assertEqual(union.tags, [int, bool])
AssertionError: Lists differ: [<type 'bool'>, <type 'int'>] != [<type 'int'>, <type 'bool'>]

First differing element 0:
<type 'bool'>
<type 'int'>

- [<type 'bool'>, <type 'int'>]
+ [<type 'int'>, <type 'bool'>]

----------------------------------------------------------------------
Ran 19 tests in 0.035s

FAILED (failures=1)
