### ISSUE TITLE
problem with the lambdas

### ISSUE THREAD

**Issue by etosch** [ameetrivedi/bocado#6]
There's a known issue with lambdas and how functions are uniquely identified: they use line number and name, but if you have two lambdas on the same line, you get into trouble, e.g.:

`def foo(arg1=lambda..., arg2=lambda...`

will first identify foo, then will identify arg1, which will have the name "<lambda>", and then choke at arg2. The same problem shows up here:

`a, b = lambda x : ..., lambda y: ...`

**Comment by ameetrivedi** [comment]
Ignore the above message stating "ameetrivedi referenced this issue from a commit". It is because of a typo in earlier commit where the issue # referenced in commit message was #6 instead of #3. I have still not looked into this issue yet.

**Comment by ameetrivedi** [comment]
Need to sit with Emma for this issue resolution

**Comment by etosch** [comment]
Revisiting the code, I think it's better for us to punt on this right now. I updated my fork to ignore anonymous functions for now. I think that's better than having a partially correct solution. Since we aren't looking at inference for local variables, I think this will generally be okay (with the exception of anonymous functions that appear at the module level and those that are returned and/or reset globals, which I imagine is a very small part of any code base).

We can address this later, after we have the convergence stuff integrated.
